/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package financialindicators;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import financialindicators.dto.request.IndicatorRequestDto;
import financialindicators.dto.response.IndicatorResponseDto;
import financialindicators.services.FinancialIndicatorService;
import financialindicators.services.MapperIndicatorService;
import org.jsoup.nodes.Document;

import financialindicators.config.JsoupConfig;

public class App {

    public static void main(String[] args) {

        HashMap<String, String> indicatorsMap = new HashMap<>();

        try {
            //TODO: dolar
            Document dolarDocument = JsoupConfig.getConnection("https://valordeldolar.cl/");
            String dolarContent = JsoupConfig.getElementBySite(dolarDocument, "vd");

            //TODO: euro
            Document euroDocument = JsoupConfig.getConnection("https://valordeleuro.cl/");
            String ueroContent = JsoupConfig.getElementBySite(euroDocument, "vd");

            //TODO: uf
            Document ufDocument = JsoupConfig.getConnection("https://valoruf.cl/");
            String ufContent = JsoupConfig.getElementBySite(ufDocument, "vpr");

            indicatorsMap.put("Dolar", dolarContent);
            indicatorsMap.put("Euro", ueroContent);
            indicatorsMap.put("UF", ufContent);

            //
            MapperIndicatorService mapperIndicatorService = new MapperIndicatorService();
            IndicatorRequestDto indicatorRequestDto = mapperIndicatorService.buildIndicatorRequestDto("dollar", "vr");

            FinancialIndicatorService financialIndicatorService = new FinancialIndicatorService();
            IndicatorResponseDto dolarIndicator = financialIndicatorService.getIndicatorOfName(indicatorRequestDto);
            //IndicatorResponseDto euroIndicator = financialIndicatorService.getIndicatorOfName("euro");
            //IndicatorResponseDto ufIndicator = financialIndicatorService.getIndicatorOfName("uf");

            List<IndicatorResponseDto> indicatorResponseDtos = new ArrayList<>();
            indicatorResponseDtos.add(dolarIndicator);

            indicatorResponseDtos.forEach(System.out::println);


            indicatorsMap.forEach((key, value) -> System.out.println(key + " " + value));

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


    }
}
